#+title: Resume
#+options: title:nil toc:nil num:nil author:nil creator:nil timestamp:nil html-style:nil
#+HTML_HEAD: <link rel="stylesheet" href="./style.css">

* Kanishak Vaidya
:PROPERTIES:
:HTML_CONTAINER_CLASS: personal
:END:
*Address:* B Block, IISc Bangalore, Bengaluru, Karnataka. 560012
| *E-mail:* [[mailto:kanishakvaidya@gmail.com][kanishakvaidya@gmail.com]]  | *Website:* [[https://kanishakvaidya.github.io/phd-progress/][kanishakvaidya.github.io/phd-progress/]] |
* Academic Achievements and Scholarships
:PROPERTIES:
:HTML_CONTAINER_CLASS: sidecol
:END:
 - Granted *PMRF*: January 2020
 - GATE (EC) 2018: *AIR 10. GATE Score: 1000*
 - *Junior Mathematical Olympiad:* 2011. AIR 30
** Professional Skills
 - Research and analysis
 - Teaching and mentoring
 - Scientific writing
 - Critical thinking
** Technical Strengths
 - *Programming:* C/C++, Python, Octave/MATLAB, Bash scripting
 - *Software Tools:* Proteus, LabView, Arduino IDE, SimuLink
 - *Miscellaneous:* Linux, SSH, git, LaTeX, Markdown/Pandoc, vim, emacs
** Industrial Experience
 - *BSNL Mandi:* 45 Day industrial training on /telephone exchange/, /main distribution frames/ and /switching/.
 - *RWIT:* Workshop on wireless technologies, IoT and 5G
 - *INMOTC:* KV Dhaula Kuan, Delhi. Focus on Complex analysis, Number theory and geometry

#+begin_export html
<button class="printme"><a href="https://kanishakvaidya.github.io/resume/resume.pdf">Download CV</a></button>
#+end_export

* About me
:PROPERTIES:
:HTML_CONTAINER_CLASS: maincol
:END:
As a Ph.D. fellow in the Electrical Communication Engineering department at IISc Bangalore, I specialize in private information retrieval, cache-aided networks, and distributed systems. My research is focused on addressing privacy concerns in distributed systems and developing new techniques for straggler mitigation. I have a strong background in coding, signal processing, and information theory and I have also worked on image processing and computer vision projects.
** Recent Publications
 - Kanishak Vaidya and B. Sundar Rajan, *``Cache-Aided Multi-User Private Information Retrieval Using PDAs,''* 2023 IEEE Information Theory Workshop (ITW), Saint-Malo, France, 23-28 April 2023.
 - Kanishak Vaidya and B. Sundar Rajan, *``Private Information Delivery with Coded Storage,''* 2022 - 2022 IEEE International Symposium on Information Theory (ISIT 2022), Espoo, Finland, 24 June – 2 July 2022.
 - Kanishak Vaidya and B. Sundar Rajan, *``Cache-Aided Multi-Access Multi-User Private Information Retrieval,''* 2022 20th International Symposium on Modeling and Optimization in Mobile, Ad hoc, and Wireless Networks (WiOpt), Torino, Italy, 2022, pp. 246-253, doi: 10.23919/WiOpt56218.2022.9930597.
 - *Other publications*: [[https://kanishakvaidya.github.io/phd-progress/publications][kanishakvaidya.github.io/phd-progress/publications]]
   + Kanishak Vaidya and B. Sundar Rajan, *``Distributed Computation: Privacy, Straggler Mitigation, and Security Against Colluding Workers,''* 2020 - 2020 IEEE Global Communications Conference, 2020, pp. 1-6, doi: 10.1109/GLOBECOM42002.2020.9322092.
   + Kanishak Vaidya and B. Sundar Rajan, *``Cache-Aided Multi-User Private Information Retrieval using PDAs.''* arXiv:2212.12979, 26 December 2022.
   + Kanishak Vaidya and B. Sundar Rajan, *``Multi-Access Cache-Aided Multi-User Private Information Retrieval,''* arXiv:2201.11481, 9 Feb 2022.
   + Kanishak Vaidya and B. Sundar Rajan, *``Private Information Delivery with Coded Storage,''* arXiv:2202.03803, 8 Feb 2022.
** Projects
 - Image segmentation using watershed transform
 - Image mosaic using homography estimation
 - *Hobby projects:* Maintain a Linux distribution and package repository
 - *Other projects:* [[https://kanishakvaidya.github.io/phd-progress/projects/index.html][kanishakvaidya.github.io/phd-progress/projects]]
   + *Computer vision*: Camera rotation and translation from images
   + *Arduino based* Two-wheel self balancing robot
   + *Arduino based* Plant self care system
   + *ATmega2560* based Pizza delivery system
   + Gesture controlled wheelchair
   + Home security alarm from *LDR and BJT Transistors*
** Education
|  *PhD, M.Tech*  |      IISc Bangalore      | Aug 2018 - Present  | CGPA: 8.9/10 |
|    *B.Tech*     |    JNGEC Sundernagar     | Aug 2013 - Jul 2017 |    69.4%     |
|     *10+2*      | Kendriya Vidyalaya Mandi |       2012-13       |    85.4%     |
| *Matriculation* | Kendriya Vidyalaya Mandi |       2010-11       | CGPA: 9.2/10 |
